### ISSUE TITLE
README.md Compatibility section - bump Android version number?

### ISSUE THREAD

**Issue by bastianilso** [nextcloud/android-library#1417]
Hi,

According to the README.md, Nextcloud's android-library is backwards compatible down to Android version 3.0 and if that's still true, that's great! However, I suspect this number may need to be bumped up to Android 7.0 Nougat (unfortunately)?

Background:
I own two older Android devices running Android 6 Marshmallow, where Nextcloud hasnt updated since [3.26.x](https://github.com/nextcloud/android/releases/tag/stable-3.26.0) in September 2023 - later Nextcloud 3.27.x and above only support Android 7 (Nougat) and above, since [this commit](https://github.com/nextcloud/android/commit/b1daecac7089fc7fc579d735df03a97baf513c97) (bumping minimum target from API 33 Marshmallow to API 34 Nougat). I tried to compile the Nextcloud app prior to this bump, but received these messages:

```
Dependency 'androidx.core:core-ktx:1.12.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.
```

Gradle's dependency graph indicated that this came from `com.github.nextcloud:android-library:master-SNAPSHOT` and `git blame` indicated that core-ktx was bumped from 1.10.1 to 1.12.0 in commit 0ad0d27 in android-library.

Anyway, this might just have been a misinterpretation on my part,  I'm very new to the nextcloud codebases and Gradle. :-)

**Comment by AndyScherzinger** [comment]
There are two different things here

* The library: see https://github.com/nextcloud/android-library/blob/master/library/build.gradle#L141 has compile target 14
* The actual client using this library targets Android 7+ due to the general Android version distribution and Android-version min-version requirements.

We drop Android versions for the client app (not the lib) when the usage rate for the app drops below 0.5%. This is needed in order to sometimes even update some libraries and we are currently already stuck again on some older lib versions due to supporting Android 7. So when that drops below 0.5% than we drop drop it and go for Android 8 as the new min-version for the app.

**Comment by bastianilso** [comment]
I see, Thank you for this clarification!
